COLORS_IDENTITY = {
    'U': 'Blue',
    'R': 'Red',
    'W': 'White',
    'B': 'Black',
    'G': 'Green',
    'UW': 'Azorius',
    'BU': 'Dimir',
    'BR': 'Rakdos',
    'GW': 'Selesnya',
    'BW': 'Boros',
    'RU': 'Izzet',
    'BG': 'Golgari',
    'BUW': 'Esper',
    'BRU': 'Grixis',
    'BGR': 'Jund',
    'GRW': 'Naya',
    'GUW': 'Bant',
    'BGW': 'Abzan',
    'RUW': 'Jeskai',
    'BGU': 'Sultai',
    'BRUW': 'Yore-Tiller',
    'BGRU': 'Glint-Eye',
    'BGRW': 'Dune-Brood',
    'GRUW': 'Ink-Treader',
    'BGUW': 'Witch-Maw'
}

ALLOWED_FORMATS = set(["commander","standard","modern","pioneer","pauper"])
BASIC_LANDS = set(["plains","mountain","forest","swamp","island"])
TYPES_TOKENIZER = {
    'creature': 0, 
    'instant': 1, 
    'sorcery': 2, 
    'enchantment': 3, 
    'artifact': 4, 
    'planeswalker': 5, 
    'plane': 6, 
    'scheme': 7, 
    'artifact creature': 8, 
    'land': 9, 
    'emblem': 10, 
    'vanguard': 11, 
    'sorcery // sorcery': 12, 
    'enchantment creature': 13, 
    'instant // instant': 14, 
    'enchantment artifact': 15, 
    'host creature': 16, 
    'instant // sorcery': 17, 
    'stickers': 18, 
    'sorcery // instant': 19, 
    'instant // land': 20, 
    'battle': 21, 
    'enchantment //  land': 22, 
    'sorcery // land': 23, 
    'instant // sorcery // sorcery': 24, 
    'dungeon': 25, 
    'artifact //  land': 26,
    'conspiracy': 27, 
    'artifact // creature': 28, 
    'artifact // land': 29, 
    'hero': 30, 
    'card // dungeon': 31, 
    'artifact land': 32, 
    'hero artifact': 33, 
    'instant creature': 34, 
    'ongoing scheme': 35, 
    'land //  land': 36, 
    'phenomenon': 37, 
    'artifact // artifact': 38, 
    'artifact // sorcery': 39, 
    'elite creature': 40, 
    'enchantment // enchantment': 41, 
    'enchantment land': 42, 
    'sorcery // creature': 43
}