version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PROJECT_DB_USER}
      POSTGRES_PASSWORD: ${PROJECT_DB_PASSWORD}
      POSTGRES_DB: ${PROJECT_DB_NAME}
      POSTGRES_ROOT_PASSWORD: ${PROJECT_DB_ROOT_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data