"""add commander fields


Revision ID: 214aafc28acf
Revises: 54dc5a1b386d
Create Date: 2023-12-25 15:10:35.911460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214aafc28acf'
down_revision: Union[str, None] = '54dc5a1b386d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commander',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('card_deck', sa.Column('is_commander', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_deck', 'is_commander')
    op.drop_table('commander')
    # ### end Alembic commands ###
