"""fix typo en el modelo

Revision ID: 54dc5a1b386d
Revises: 9ef18e511929
Create Date: 2023-12-04 22:07:38.400823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54dc5a1b386d'
down_revision: Union[str, None] = '9ef18e511929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('tournament', sa.Integer(), nullable=True))
    op.drop_constraint('standings_Tournament_fkey', 'standings', type_='foreignkey')
    op.create_foreign_key(None, 'standings', 'tournaments', ['tournament'], ['id'])
    op.drop_column('standings', 'Tournament')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings', sa.Column('Tournament', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'standings', type_='foreignkey')
    op.create_foreign_key('standings_Tournament_fkey', 'standings', 'tournaments', ['Tournament'], ['id'])
    op.drop_column('standings', 'tournament')
    # ### end Alembic commands ###
