"""inicio

Revision ID: 7928db44432f
Revises: 
Create Date: 2023-10-15 21:47:19.364647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7928db44432f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scryfall_id', sa.String(length=250), nullable=False),
    sa.Column('edhc_rank', sa.Float(), nullable=True),
    sa.Column('penny_rank', sa.Float(), nullable=True),
    sa.Column('commander_legal', sa.Boolean(), nullable=True),
    sa.Column('standard_legal', sa.Boolean(), nullable=True),
    sa.Column('modern_legal', sa.Boolean(), nullable=True),
    sa.Column('pioneer_legal', sa.Boolean(), nullable=True),
    sa.Column('pauper_legal', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=250), nullable=False),
    sa.Column('scry_fall_id', sa.String(length=250), nullable=False),
    sa.Column('is_spoiler', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('mana_cost', sa.String(length=250), nullable=True),
    sa.Column('colors', sa.String(length=250), nullable=True),
    sa.Column('cmc', sa.String(length=250), nullable=True),
    sa.Column('color_identity', sa.String(length=250), nullable=True),
    sa.Column('type_line', sa.String(length=250), nullable=True),
    sa.Column('is_legendary', sa.Boolean(), nullable=True),
    sa.Column('is_snow', sa.Boolean(), nullable=True),
    sa.Column('main_type', sa.String(length=250), nullable=False),
    sa.Column('sub_type', sa.String(length=250), nullable=False),
    sa.Column('power', sa.String(length=250), nullable=True),
    sa.Column('toughness', sa.String(length=250), nullable=True),
    sa.Column('produced_mana', sa.String(length=250), nullable=True),
    sa.Column('key_words', sa.JSON(), nullable=True),
    sa.Column('oracle_text', sa.Text(), nullable=True),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card', sa.Integer(), nullable=True),
    sa.Column('set', sa.Integer(), nullable=True),
    sa.Column('small_front_img', sa.String(length=250), nullable=True),
    sa.Column('normal_front_img', sa.String(length=250), nullable=True),
    sa.Column('small_back_img', sa.String(length=250), nullable=True),
    sa.Column('normal_back_img', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['card'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['set'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print', sa.Integer(), nullable=True),
    sa.Column('usd', sa.Float(), nullable=True),
    sa.Column('eur', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=250), nullable=True),
    sa.Column('is_foil', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['print'], ['prints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('prints')
    op.drop_table('card_faces')
    op.drop_table('sets')
    op.drop_table('cards')
    # ### end Alembic commands ###
