"""fix typo en el modelo

Revision ID: 9ef18e511929
Revises: ecc908aa17b5
Create Date: 2023-12-04 22:04:13.503667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef18e511929'
down_revision: Union[str, None] = 'ecc908aa17b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_deck', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('card_deck', 'cuantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_deck', sa.Column('cuantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('card_deck', 'quantity')
    # ### end Alembic commands ###
