"""se agregaron los torneos

Revision ID: c1a5f73f3fb7
Revises: 20cb5c572bba
Create Date: 2023-11-29 21:55:32.117536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a5f73f3fb7'
down_revision: Union[str, None] = '20cb5c572bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
