"""nuevos campos

Revision ID: c746c27b3a08
Revises: d5c275da4133
Create Date: 2023-10-16 12:02:49.795203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c746c27b3a08'
down_revision: Union[str, None] = 'd5c275da4133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prints', sa.Column('reprint', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prints', 'reprint')
    # ### end Alembic commands ###
