"""nuevos campos

Revision ID: d5c275da4133
Revises: 7928db44432f
Create Date: 2023-10-16 12:01:57.817987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5c275da4133'
down_revision: Union[str, None] = '7928db44432f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prints', sa.Column('rarity', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prints', 'rarity')
    # ### end Alembic commands ###
